name: Galaxy Tool CI/CD Pipeline

on:
  workflow_call:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Push events to tags matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  
  deploy:
    # needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create Planemo config
        env:
          USER: ${{ secrets.TOOLSHED_USER_NAME }}
          KEY: ${{ secrets.TOOLSHED_API_KEY }}
          EMAIL: ${{ secrets.TOOLSHED_EMAIL }}
          PASS: ${{ secrets.TOOLSHED_PASS }}
        run: |
          mkdir -p $HOME/.planemo
          cat > $HOME/.planemo.yml << EOF
          shed_username: $TOOLSHED_USER_NAME # your ToolShed username
          sheds:
            toolshed:
              key: $TOOLSHED_API_KEY        # your ToolShed API key, under 'User > API Keys'
              email: $TOOLSHED_EMAIL    # your ToolShed email
              password: $TOOLSHED_PASS  # your ToolShed password
          EOF

      - name: Install Planemo
        run: pip install planemo

      - name: Update Tool Shed
        run: planemo shed_update -r --shed_target toolshed